### ISSUE TITLE
Multigraph plugins does not opens from hosts view

### ISSUE THREAD

**Issue by OlegPS** [jonnymccullagh/munstrap#14]
In hosts view, nothing happens when you click on tab with multigraphs in it. I have such issue on proc plugin. nothing changed with click on "process info"

**Comment by jonnymccullagh** [comment]
Oleg, It is probably due to the space within "process info". I had this issue too. I changed the name of the group to remove the space in the graph_category variable in any plugins. My aim was to create the templates without having to touch any of the core munin code - there have been some compromises.
